[server]
enableStaticServing = true

# Bold and stylish font options - choose one of these setups:

# Option 1: Poppins (Modern, bold, very stylish)
[[theme.fontFaces]]
family = "Poppins"
url = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap"

# Option 2: Montserrat (Clean, bold, professional)
# [[theme.fontFaces]]
# family = "Montserrat"
# url = "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"

# Code font - JetBrains Mono (stylish monospace)
[[theme.fontFaces]]
family = "JetBrains Mono"
url = "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&display=swap"

[theme]
primaryColor = "#cb785c"
backgroundColor = "#fdfdf8"
secondaryBackgroundColor = "#ecebe3"
textColor = "#3d3a2a"
linkColor = "#3d3a2a"
borderColor = "#d3d2ca"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full"
font = "Poppins"
# Bold and stylish font weights
headingFontWeights = [800, 700, 600, 600, 500, 500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "JetBrains Mono"
codeFontSize = ".75rem"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true
chartCategoricalColors = ["#0ea5e9", "#059669", "#fbbf24"]

[theme.sidebar]
backgroundColor = "#f0f0ec"
secondaryBackgroundColor = "#ecebe3"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
dataframeHeaderBackgroundColor = "#e4e4e0"
